### ISSUE TITLE
Duplicated Menu Items in Developer Documentation

### ISSUE THREAD

**Issue by pmkay** [cardano-foundation/developer-portal#1075] opened 2023-06-02 15:52 UTC
Hi,

I've noticed that there are duplicated menu items in the developer documentation. This is causing some confusion when trying to navigate through the documentation.

##Steps to Reproduce
Navigate to the Developer Documentation section of our website/application.
Look at the menu items on the left-hand side.

## Expected Behavior
Each menu item should be unique, presenting the user with distinct topics and subtopics.

## Actual Behavior
Certain menu items are duplicated, causing confusion and redundancy in the navigation of the documentation.

## Possible Solution
Ensure uniqueness in each menu item.

## Additional Information
![image](https://github.com/cardano-foundation/developer-portal/assets/4557167/6cb19ff8-ff07-4744-b6a8-fc893520911f)

Looking forward to the updated documentation.

Thanks

**Comment by fill-the-fill** [comment] 2023-06-02 17:19
Hey! I will take a look and take care of that :)

**Comment by rphair** [comment] 2023-06-02 18:30
I was thinking this could have been caused by https://github.com/cardano-foundation/developer-portal/pull/1066, which changed target branches at the last minute before merging, but that didn't affect this part of `sidebars.js` as confirmed in the diff for that PR.

I can only confirm that the duplicates are also in the locally built `staging`, not just in the live site. 🤔

**Comment by eoswins** [comment] 2023-06-04 02:59
Just want to also add there is duplicate text on https://developers.cardano.org/docs/get-started/running-cardano :

 You might be asking what the difference is between mainnet and testnet and why there are two official network types? To put it simply, Cardano is an open-source blockchain, and anyone is free to spin up a network based on Cardano's software components. The mainnet network was the first one established during the start of the Byron era in 2017. And everyone participating in the network agreed that is where all the real value of Cardano lives. You might be asking what the difference is between mainnet and testnet and why there are two official network types? To put it simply, Cardano is an open-source blockchain, and anyone is free to spin up a network based on Cardano's software components. The mainnet network was the first one established during the start of the Byron era in 2017. And everyone participating in the network agreed that is where all the real value of Cardano lives.

**Comment by rphair** [comment] 2023-06-09 19:31
thanks @eoswins - reported with a temporary fix in https://github.com/cardano-foundation/developer-portal/pull/1083 but certainly seems we need to continue our investigation about how this happened.  @fill-the-fill strangely it looks like some commits may have been applied twice... something I haven't seen since the early days of `git` and its predecessors 😰

**Comment by fill-the-fill** [comment] 2023-07-24 09:28
Fixed in #1090

**Closed** 2023-07-24 09:27 UTC
