### ISSUE TITLE
Seems "Generate Stake Pool Keys" page is not necessary?

### ISSUE THREAD

**Issue by os11k** [cardano-foundation/developer-portal#374] opened 2021-10-17 11:19 UTC
If we look into Stake Pool Course - Handbook - Generate Stake Pool Keys

It seems this page is just duplicate of "Create Stake Pool Keys" page and I think this page is not necessary. Or Am I wrong?

Why do you need to create stake pool keys again if we made them them in "Create Stake Pool Keys" page?

**Comment by katomm** [comment] 2022-02-02 11:58
I believe we need a complete rewrite of the stake pool course, new structure and everything. If anyone wants to team up on this please let me know.

**Comment by erickl17** [comment] 2022-02-17 01:56
"Stake Pool Course - Handbook - Generate Stake Pool Keys" is supposed to have the information on how to Generate Cold Keys and Cold Counter, VRF Key Pair, KES Key Pair, and Operational Certificate. For some reason it is a duplicate of "Create Stake Pool Keys".

**Comment by os11k** [comment] 2022-12-07 15:10
I think that can be closed and should will be fixed by #737 

@katomm, what do you think?

**Comment by katomm** [comment] 2022-12-07 21:06
Yes, I think so too.

**Closed** 2022-12-08 11:42 UTC
Labels: stake pool operators
