### ISSUE TITLE
Broken links in Integrate Cardano page.

### ISSUE THREAD

**Issue by sriveros** [cardano-foundation/developer-portal#487] opened 2022-01-19 22:38 UTC
**[Integrate Cardano](https://developers.cardano.org/docs/integrate-cardano/)**
Broke links:
[Explore Cardano wallets](https://developers.cardano.org/docs/creating-wallet-faucet)
[Multi-witness transactions](https://developers.cardano.org/docs/multi-witness-transactions-cli)
[Listening for ada payments using cardano-cli](https://developers.cardano.org/docs/listening-for-payments-cli)
[Listening for ada payments using cardano-wallet](https://developers.cardano.org/docs/listening-for-payments-wallet)
[Testnet Faucet](https://developers.cardano.org/docs/testnet-faucet)

**Comment by Dimitri4540** [comment] 2022-01-20 13:40
Need to add /integrate-cardano/ in path

X -> https://developers.cardano.org/docs/creating-wallet-faucet
V -> https://developers.cardano.org/docs/integrate-cardano/creating-wallet-faucet

**Comment by katomm** [comment] 2022-02-01 12:03
Thanks for flagging @sriveros. Unfortunately, I cannot reproduce the problem. I quickly run a dead link checker on https://developers.cardano.org/docs/integrate-cardano/ and 62 links on the site are working.

**Comment by katomm** [comment] 2022-02-08 08:37
I'm closing this now, would be nice if you can confirm.

**Closed by katomm** 2022-02-08 08:37 UTC
